version: "3.9"
services:

#  go:
#    build: ./go
#    ports:
#      - "8080:8080"
#    networks:
#      - some-net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes: 
      - ./PostgresDB:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresqODl/data
    networks:
      - some-net

networks:
  some-net:
    driver: bridge
